version: "3.9"

services:
  retroiptvguide:
    container_name: retroiptvguide
    image: ghcr.io/thehack904/retroiptvguide:latest
    restart: unless-stopped
    ports:
      - "5000:5000"
    env_file:
      - .env
    volumes:
      - ./config:/app/config
      - ./logs:/app/logs
      - ./data:/app/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000"]
      interval: 30s
      timeout: 5s
      retries: 3
