name: RetroIPTVGuide CI/CD

on:
  push:
    branches:
      - main
      - dev
      - feature/**
  workflow_dispatch:

env:
  PYTHON_VERSION: "3.12"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Build RetroIPTVGuide
        run: |
          echo "🚧 Building RetroIPTVGuide..."
          pip install -r requirements.txt
          python -m py_compile $(find . -name "*.py")

  test:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}
      - name: Run basic tests
        run: |
          echo "🧪 Running syntax and basic runtime tests..."
          python -m unittest discover -s tests || echo "No tests found, skipping."

  deploy:
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/dev'
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to dev server
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.DEPLOY_SSH_KEY }}
          source: "."
          target: "/opt/retroiptvguide-dev"
